site_name: '<img src="/logo/SynthetaLogoDarkfont4.png" style="width: 250px; height: auto; vertical-align: middle;">'

extra_css: 
  - custom.css

theme:
  name: 'mkdocs'
  color_mode: auto
  user_color_mode_toggle: true
  locale: en  
  separator: "_"
  palette:
    primary: 'indigo'
  font:
    text: 'Roboto, sans-serif '
    code: 'Courier New, monospace'

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes



search:
  search_index_only: true
  
nav:
  - ğŸ°Home: home/home.md
  - ğŸ“ŠCreate Dashboard: create_dashboard/create_dashboard.md
  - ğŸ‘¤Add Role: add_role/add_role.md
  - ğŸ‘¥Add User: add_user/add_user.md
  - ğŸ”ŒDB Connection: DB_connection/DB_connection.md
  - ğŸ“¤File Upload: file_upload/file_upload.md
  - ğŸ”—Table Join: table_join/table_join.md
  - âš™ï¸Dashboard setup: dashboard_setup/dashboard_setup.md


# copyright: Copyright &copy; 2024 <a href="https://idamtat.in/">IDAMTAT</a>, Maintained by the <a href="https://wyzmindz.com/">IDAMTAT TECHNOLOGIES & SERVICES LLP</a>.

copyright: |
  <div style="text-align:center;">
    <p>Copyright Â© 2024 <a href="https://idamtat.in/" target="_blank" style="color: Black;font-weight: bold;">IDAMTAT</a>, Maintained by 
    <a href="https://wyzmindz.com/" target="_blank" style="color: black;font-weight: bold;">IDAMTAT TECHNOLOGIES & SERVICES LLP</a>.</p>
  </div>

# For more information, hover over the 
# <a href="#" class="tooltip">button
#   <span class="tooltiptext">This is extra info about the button!</span>
# </a>.

